org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m

android.useAndroidX=true

reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64

android.disallowKotlinSourceSets=false
hermesEnabled=true

MYAPP_UPLOAD_STORE_FILE=pdfmaker.keystore
MYAPP_UPLOAD_KEY_ALIAS=pdfmaker
MYAPP_UPLOAD_STORE_PASSWORD=pdfmaker0
MYAPP_UPLOAD_KEY_PASSWORD=pdfmaker0